# output dir will be created by hydra
data_dir: /eos/home-s/ssaha/JetSSL_Unige/inputs_h5/
#output_dir: /srv/beegfs/scratch/groups/rodem/jetssl/
output_dir: /eos/home-s/ssaha/JetSSL_Unige/jetssl/test_1/

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
